### PR TITLE
issue 159 : Gxe editor on JBoss

### PR DESCRIPTION
**Pull request by g3r4n**
Gxe editor load gxe difinition file with wrong url on JBoss

### CODE REVIEW

**Comment by g3r4n** [comment]
To make it works i've create a folder content in <Jboss-install-rep>/bin and copy geoportal.war in <Jboss-install-rep>/bin/content .

**Comment by mhogeweg** [comment]
We'll look at this fix. thanks.

**Comment by umacgillivray** [comment]
@g3r4n @mhogeweg 
The pull request also contains a modification to com/esri/gpt/framework/security/identity/agp/PortalIdentityAdapter.java, was that intended?

**Comment by g3r4n** [comment]
the change in com/esri/gpt/framework/security/identity/agp/PortalIdentityAdapter.java are realted to the issue 168 :https://github.com/Esri/geoportal-server/issues/168
sorry for the mess

**Comment by umacgillivray** [comment]
@g3r4n 
Thx, we'll incorporate your jboss/vfs change, but I can't reproduce the double encoded user@domain issue, I've tried with an ArcGIS online account and a Portal for ArcGIS 10..3.1 account, both are working ok for me. Are you using Portal's identity store or an LDAP? Maybe it's specific to your configuration. I could make the decode() conditional (i.e. only decode if a certain gpt.xml parameter is set to true).

**Comment by g3r4n** [comment]
We are using portal as an identity store. This store, store user from an active directory. These user have a double encoded user@domain issue.

**Pull request merged**
